// Auto-generated by scripts/generate-environment.mjs — do not edit manually.
// Copy .env.example to .env and run npm start / npm run build.

export const environment = {
  production: false,
  apiBaseUrl: 'http://localhost:8000/api/v1',
  frontendUrl: 'http://localhost:4200',
};
