// Auto-generated by scripts/generate-environment.mjs — do not edit manually.
// Copy .env.example to .env and run npm start / npm run build.

export const environment = {
  production: true,
  apiBaseUrl: 'https://medicalrag-kz18.onrender.com/api/v1',
  frontendUrl: 'https://medical-rag-constrained.vercel.app',
};
