# # Test to determine if the llm is better off with the pipeline or without factually

# from llama_cpp import Llama
# from apps.api.app.core.logger_setup import time_metrics, CentralizedLogger

# logger = CentralizedLogger.get_logger(__name__)

# MODELS = [
#     # "qwen_coder2_3b":"/home/ubuntu/.ollama/models/blobs/sha256-4a188102020e9c9530b687fd6400f775c45e90a0d7baafe65bd0a36963fbb7ba",
#     {"name": "qwen_0.5b", "loc" : "/home/ubuntu/.ollama/models/blobs/sha256-c5396e06af294bd101b30dce59131a76d2b773e76950acc870eda801d3ab0515"},
#     {"name": "qwen_1.5b", "loc" : "/home/ubuntu/.ollama/models/blobs/sha256-183715c435899236895da3869489cc30ac241476b4971a20285b1a462818a5b4"},
#     {"name": "qwen_3b",   "loc" : "/home/ubuntu/.ollama/models/blobs/sha256-5ee4f07cdb9beadbbb293e85803c569b01bd37ed059d2715faa7bb405f31caa6"}
# ]

# PROMPT = '''
#     Ill be provisioning you with lab data for a certain patient
#     Generate a concise, precise and complete summary of the patient's medical information, including:
#     1. Key findings from the extracted text.
#     2. Summary of diseases and their severity levels.
#     3. Summary of laboratory results, highlighting important test names, values, units, and normal ranges.
#     4. Any mismatches.
#     Note: Dont add extra information that is not in the given input

#     Objective: Create a comprehensive summary that highlights the main points of the patient's medical information in an easy-to-understand format for healthcare providers.
# '''

# @time_metrics()
# def summarize(patient_data, prompt, model):
#     try:
#         client = Llama(
#             model_path=model,
#             n_ctx=12288,
#             n_threads=2,
#             chat_format='qwen',
#             verbose=False
#         )

#         stream = client.create_chat_completion(messages=[
#             {'role' : 'system', 'content': prompt},
#             {'role': 'user', 'content': patient_data}
#         ])

#         return stream["choices"][0]['message']['content']
    
#     except Exception as e:
#         logger.error("Error occurred during summrization: {e}")
#         raise

# lab_result1 = """
# LABORATORY REPORT - CONFIDENTIAL
# PATIENT ID: JD-99283-X
# NAME: JOE, Doe (Patient)
# DOB: 04/12/1985 (Age: 40)
# Sex: M
# COLLECTED: 2026-03-22T14:30:00Z
# RECEIVED: Mar 23, '26 @ 09:15 AM
# ORDERING PHYSICIAN: Dr. Smith, MD (NPI: 1234567890)

# SUMMARY OF RESULTS
#  Test Name  Result  Units  Flag  Reference Range 
#  Glucose, Fasting  104  mg/dL  H  [70 - 99]
#  Hemoglobin A1c  5.8  %  !  < 5.7 
#  Creatinine  1.25  mg/dl   0.70 - 1.30 
#  Potassium  5.6  mEq/L  CRITICAL  3.5 - 5.1 
#  Sodium  140  mmol/l   135-145 
#  WBC Count  11.2  x10^3/uL  HIGH  4.5-11.0 

# DETAILED ANALYTE DATASection: METABOLIC_PANEL_REVISED

# * Calcium: 9.2 (Ref: 8.5-10.2 mg/dL)
# * BUN: 18 mg/dL
# * eGFR: >60 mL/min/1.73m2 (Note: Non-African American)
# * ALT (SGPT): 45 U/L [Range: 0-44] (ABNORMAL)

# Section: LIPID_PROFILE (FASTING: YES)

# * TOTAL CHOLESTEROL: 215 mg/dL (Flag: BORDERLINE)
# * HDL: 42 mg/dL
# * LDL (Calculated): 145 mg/dL
# * Method: Friedewald Equation used for calculation.
# * TRIGLYCERIDES: 140 mg/dL

# LAB NOTES & COMMENTS

# TECH NOTE (03/23): Specimen for Potassium was slightly hemolyzed. Result may be falsely elevated. Suggest redraw if clinically indicated.
# DISCLAIMER: This report was generated by an automated system. Please verify all CRITICAL values with the lab director.
# Location: Northside General Lab - 123 Lab Way, Suite 400.
# Report Status: Final (Amended 03/24/2026 for corrected spelling of patient last name)."""


# lab_result2 = """
# L@B0R4T0RY R3P0RT (v.2.1-beta)
# Ref ID: [SCAN_ERR_042]  UUID: 550e8400-e29b-41d4-a716-446655440000
# PATIENT_INFO_BLOCK

# * NOM: Doe / PRÉNOM: Joe
# * D.O.B.: 12-APR-1985 (Format: DD-MMM-YYYY)
# * GENDER: M  Hgt: 180cm  Wgt: 85kg
# * ADDR: 123 Main St, "Apt 4B", Springfield, OR, 97477 (Note: contains quotes and commas)

# 🧪 BIO-CHEMICAL ANALYSIS [SECTION_ID: 99]

#  Component [1]  Value  Unit  Status  Ref_Range 

#  Glucose  104.00  mg/dL  ❗  70.0 - 99.9 
#  HbA1c  5,8  %  Abn  <5.7 
#  Potassium  6.1  mEq/L  CRITICAL_HIGH  3.5-5.1 
     
#  LIPIDS_SUBTABLE     
#  > Total_Chol  215  mg/dL  High  100-199 
#  > LDL  145  mg/dL  [!]  <100 
#  > HDL  42  mg/dL  Low_Ok  >40 

# DATA EXTRACTION STRESSORS (DEBUG)

#    1. Inconsistent Decimals: Uses both . (104.00) and , (5,8) as decimal separators.
#    2. Nested Table Hack: The LIPIDS_SUBTABLE is embedded inside the main table structure using empty cells and > prefixing.
#    3. Broken Date Logic: Header uses DD-MMM-YYYY, but the footer might use YYYY.MM.DD.
#    4. Mixed Languages: "NOM" (French) vs "GENDER" (English).
#    5. Non-Standard Units: x10^3/uL vs cells/mm3 (see below).

# SECTION: HEMATOLOGY (OCR_ARTIFACTS_PRESENT)

# * WBC: 12.5 K/uL [Ref: 4.0-11.0]
# * RBC: 4.82 M/uL
# * HGB: 14.2 g/dL
# * PLT: 145 10*3/mcL (Note: Uses asterisk for exponent)

# LAB_COMMENTS_NULL_TERMINATED
# ERR: Field [Comments] contains unescaped characters: "Patient reported 'feeling dizzy'; BP was 140/90."
# [SYSTEM_NOTE]: Hemolysis detected in Potassium sample. Result 6.1 might be skewed +15%.
# Verified_By: Dr. J. Smith_ID#9821
# Report Printed: 2026.03.24 @ 14:49:10
# """

# LAB_SAMPLES = [
#     {"name": "sample_1", "file": lab_result1},
#     {"name": "sample_2", "file": lab_result2}
# ]

# import pathlib
# import os

# os.makedirs("test_results/llm", exist_ok=True)

# for model in MODELS:
#     for lab_sample in LAB_SAMPLES:
#         result = summarize(lab_sample['file'], PROMPT, model['loc'])

#         directory_path = pathlib.Path(f'test_results/llm/{model['name']}')

#         if not directory_path.exists():
#             os.makedirs(directory_path)

#         file = pathlib.Path(f'{directory_path}/{lab_sample['name']}.md')

#         with open(file , 'w') as res_file:
#             res_file.write(str(result))