import re
from pathlib import Path
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter
from langchain_experimental.text_splitter import SemanticChunker
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from docling.document_converter import DocumentConverter
from datetime import datetime, timezone
from app.worker.ai_tasks.disease_extractor import extract_diseases, get_negative_entities

from app.core.logger_setup import logger, CentralizedLogger, time_metrics

logger = CentralizedLogger.get_logger(__name__)
# model_name = "dmis-lab/biobert-base-cased-v1.1"
model_name = "sentence-transformers/all-MiniLM-L6-v2"
embeddings = HuggingFaceEmbeddings(model_name=model_name)

@time_metrics()
def extract_text_from_pdf(file) -> str:
    """
    Extracts text from PDF bytes using PyMuPDF
    """

    try:
       converter = DocumentConverter()
       doc = converter.convert(file).document
       mark_doc = doc.export_to_markdown()
       

    except Exception as e:
        logger.error(f"Failed to extract text from pdf: {e}")
        raise 
    return mark_doc

@time_metrics()
def chunk_text(markdown_file):
    # headers_to_split_on = [
    # ("##", "Header 2")]
    # markdown header splitter
    # splitter = MarkdownHeaderTextSplitter(
    #    headers_to_split_on=headers_to_split_on,
    #     strip_headers=False
    # )
    # markdown header splitter
    # all_splits = splitter.split_text(markdown_file)

    splitter = SemanticChunker(
        embeddings,
        breakpoint_threshold_type="percentile",
        breakpoint_threshold_amount=80
    )

    all_splits = splitter.create_documents([markdown_file])

    # splitter = RecursiveCharacterTextSplitter(
    #    chunk_size=512,
    #    chunk_overlap=200,
    #    length_function=len,
    #    is_separator_regex=False
    # )

    # all_splits = splitter.create_documents([markdown_file])

    return all_splits

@time_metrics()
def clean_and_normalize_text(all_splits):
    """
    Clean raw text extracted from PDF before PDF processing
    """

    for i in range(len(all_splits)):
        if "Header 2" in all_splits[i].metadata and all_splits[i].metadata["Header 2"] == 'Comments':
            all_splits[i].page_content = ""

        content = all_splits[i].page_content
        cleaned = re.sub(r"\|", "",  content)
        cleaned = re.sub(r"-{2,}", "", cleaned)
        cleaned = re.sub(r"\\n", " ", cleaned)
        cleaned = re.sub(r" +", " ", cleaned)

        all_splits[i].page_content = cleaned

    return all_splits

@time_metrics()
def embed_chunks_and_store_in_vector_db(all_splits):
    """
    Embeds the Chunks generated by the Semantic Chunker. Maybe well reuse the ones created during chunking
    """
    vectorstore = Chroma.from_documents(
        all_splits,
        embeddings,
        persist_directory="./chroma_db"
    )

    return vectorstore

file_path = Path("samplePmedReport.pdf")

markdown = extract_text_from_pdf(file_path)
chunks = chunk_text(markdown)

# Path("discharge_sum.md").write_text(markdown)

for split in range(3):
    # print(f"chunk {split}\n {chunks[split]}")
    content = chunks[split].page_content
    negative_esnts = get_negative_entities(content)
    print(negative_esnts)

