# Test to determine if the llm is better off with the pipeline or without factually

from llama_cpp import Llama
from ml_core.src.ml_core.pipeline.document_reader import extract_text_from_pdf, clean_and_normalize_text, chunk_text
from ml_core.src.ml_core.pipeline.disease_extractor import get_negative_entities
from ml_core.src.ml_core.pipeline.lab_extractor import extract_labs
from ml_core.src.ml_core.pipeline.summarizer import summarize_content
from ml_core.logging_utils import time_metrics, CentralizedLogger

logger = CentralizedLogger.get_logger(__name__)

MODELS = [
    # "qwen_coder2_3b":"/home/ubuntu/.ollama/models/blobs/sha256-4a188102020e9c9530b687fd6400f775c45e90a0d7baafe65bd0a36963fbb7ba",
    # {"name": "qwen_0.5b", "loc" : "/home/ubuntu/.ollama/models/blobs/sha256-c5396e06af294bd101b30dce59131a76d2b773e76950acc870eda801d3ab0515"},
    {"name": "qwen_1.5b", "loc" : "/home/ubuntu/.ollama/models/blobs/sha256-183715c435899236895da3869489cc30ac241476b4971a20285b1a462818a5b4"},
    # {"name": "qwen_3b",   "loc" : "/home/ubuntu/.ollama/models/blobs/sha256-5ee4f07cdb9beadbbb293e85803c569b01bd37ed059d2715faa7bb405f31caa6"}
]

PROMPT = '''
    Ill be provisioning you with lab data for a certain patient
    Generate a concise, precise and complete summary of the patient's medical information, including:
    1. Key findings from the extracted text.
    2. Summary of diseases and their severity levels.
    3. Summary of laboratory results, highlighting important test names, values, units, and normal ranges.
    4. Any mismatches.
    Note: Dont add extra information that is not in the given input

    Objective: Create a comprehensive summary that highlights the main points of the patient's medical information in an easy-to-understand format for healthcare providers.
'''

lab_1 = """
LABORATORY REPORT - CONFIDENTIAL
PATIENT ID: JD-99283-X
NAME: JOE, Doe (Patient)
DOB: 04/12/1985 (Age: 40)
Sex: M
COLLECTED: 2026-03-22T14:30:00Z
RECEIVED: Mar 23, '26 @ 09:15 AM
ORDERING PHYSICIAN: Dr. Smith, MD (NPI: 1234567890)

SUMMARY OF RESULTS
 Test Name  Result  Units  Flag  Reference Range 
 Glucose, Fasting  104  mg/dL  H  [70 - 99]
 Hemoglobin A1c  5.8  %  !  < 5.7 
 Creatinine  1.25  mg/dl   0.70 - 1.30 
 Potassium  5.6  mEq/L  CRITICAL  3.5 - 5.1 
 Sodium  140  mmol/l   135-145 
 WBC Count  11.2  x10^3/uL  HIGH  4.5-11.0 

DETAILED ANALYTE DATASection: METABOLIC_PANEL_REVISED

* Calcium: 9.2 (Ref: 8.5-10.2 mg/dL)
* BUN: 18 mg/dL
* eGFR: >60 mL/min/1.73m2 (Note: Non-African American)
* ALT (SGPT): 45 U/L [Range: 0-44] (ABNORMAL)

Section: LIPID_PROFILE (FASTING: YES)

* TOTAL CHOLESTEROL: 215 mg/dL (Flag: BORDERLINE)
* HDL: 42 mg/dL
* LDL (Calculated): 145 mg/dL
* Method: Friedewald Equation used for calculation.
* TRIGLYCERIDES: 140 mg/dL

LAB NOTES & COMMENTS

TECH NOTE (03/23): Specimen for Potassium was slightly hemolyzed. Result may be falsely elevated. Suggest redraw if clinically indicated.
DISCLAIMER: This report was generated by an automated system. Please verify all CRITICAL values with the lab director.
Location: Northside General Lab - 123 Lab Way, Suite 400.
Report Status: Final (Amended 03/24/2026 for corrected spelling of patient last name)."""


lab_result1_expected = {
    "extracted_text": "LABORATORY REPORT - CONFIDENTIAL PATIENT ID: JD-99283-X NAME: JOE, Doe (Patient) DOB: 04/12/1985 (Age: 40) Sex: M COLLECTED: 2026-03-22T14:30:00Z RECEIVED: Mar 23, '26 @ 09:15 AM ORDERING PHYSICIAN: Dr. Smith, MD (NPI: 1234567890)\n\nSUMMARY OF RESULTS Test Name  Result  Units  Flag  Reference Range Glucose, Fasting  104  mg/dL  H  [70 - 99] Hemoglobin A1c  5.8  %  !  &lt; 5.7 Creatinine  1.25  mg/dl   0.70 - 1.30 Potassium  5.6  mEq/L  CRITICAL  3.5 - 5.1 Sodium  140  mmol/l   135-145 WBC Count  11.2  x10^3/uL  HIGH  4.5-11.0\n\nDETAILED ANALYTE DATASection: METABOLIC\\_PANEL\\_REVISED\n\n- Calcium: 9.2 (Ref: 8.5-10.2 mg/dL)\n- BUN: 18 mg/dL\n- eGFR: &gt;60 mL/min/1.73m2 (Note: Non-African American)\n- ALT (SGPT): 45 U/L [Range: 0-44] (ABNORMAL)\n\nSection: LIPID\\_PROFILE (FASTING: YES)\n\n- TOTAL CHOLESTEROL: 215 mg/dL (Flag: BORDERLINE)\n- HDL: 42 mg/dL\n- LDL (Calculated): 145 mg/dL\n- Method: Friedewald Equation used for calculation.\n- TRIGLYCERIDES: 140 mg/dL\n\nLAB NOTES &amp; COMMENTS\n\nTECH NOTE (03/23): Specimen for Potassium was slightly hemolyzed. Result may be falsely elevated. Suggest redraw if clinically indicated. DISCLAIMER: This report was generated by an automated system. Please verify all CRITICAL values with the lab director. Location: Northside General Lab - 123 Lab Way, Suite 400. Report Status: Final (Amended 03/24/2026 for corrected spelling of patient last name).",
    "diseases_json": [],
    "labs_json": [
        {
            "test": "GLUCOSE, FASTING",
            "value": "104",
            "unit": "mg/dL",
            "status": "H"
        },
        {
            "test": "HEMOGLOBIN A1C",
            "value": "5.8",
            "unit": "%",
            "status": "!"
        },
        {
            "test": "CREATININE",
            "value": "1.25",
            "unit": "mg/dl",
            "status": "NORMAL"
        },
        {
            "test": "POTASSIUM",
            "value": "5.6",
            "unit": "mEq/L",
            "status": "CRITICAL"
        },
        {
            "test": "SODIUM",
            "value": "140",
            "unit": "mmol/l",
            "status": "NORMAL"
        },
        {
            "test": "WBC COUNT",
            "value": "11.2",
            "unit": "x10^3/uL",
            "status": "HIGH"
        },
        {
            "test": "CALCIUM",
            "value": "9.2",
            "unit": "mg/dL",
            "status": "NORMAL"
        },
        {
            "test": "BUN",
            "value": "18",
            "unit": "mg/dL",
            "status": "NORMAL"
        },
        {
            "test": "ALT (ALT",
            "value": "45",
            "unit": "U/L",
            "status": "NORMAL"
        },
        {
            "test": "TOTAL CHOLESTEROL",
            "value": "215",
            "unit": "mg/dL",
            "status": "BORDERLINE"
        },
        {
            "test": "HDL",
            "value": "42",
            "unit": "mg/dL",
            "status": "NORMAL"
        },
        {
            "test": "LDL (CALCULATED",
            "value": "145",
            "unit": "mg/dL",
            "status": "NORMAL"
        }
    ],
    "summary_text": "### Summary of Patient's Medical Information\n\n#### Key Findings from Extracted Text:\n- The patient's blood glucose level was found to be 104 mg/dL, which is slightly elevated.\n- The patient's hemoglobin A1C level was 5.8%, indicating a moderate risk of diabetes.\n- The patient's creatinine level was within normal range at 1.25 mg/dL.\n- The patient's sodium level was 140 mmol/L, which is within normal range.\n- The patient's white blood cell count was 11.2 x10^3/uL, which is slightly elevated.\n- The patient's potassium level was not measured due to hemolysis.\n- The patient's calcium level was 9.2 mg/dL, which is within normal range.\n- The patient's BUN level was 18 mg/dL, which is within normal range.\n- The patient's ALT level was 45 U/L, which is within normal range.\n- The patient's total cholesterol level was 215 mg/dL, which is borderline high.\n- The patient's HDL level was 42 mg/dL, which is within normal range.\n- The patient's LDL level was calculated as 145 mg/dL, which is within normal range.\n\n#### Summary of Diseases and Their Severity Levels:\n- No diseases were identified in the provided information.\n\n#### Summary of Laboratory Results:\n- The patient's blood glucose level was found to be slightly elevated at 104 mg/dL, indicating a potential risk of diabetes.\n- The patient's hemoglobin A1C level was 5.8%, which suggests a moderate risk of diabetes.\n- The patient's white blood cell count was slightly elevated at 11.2 x10^3/uL, which may indicate an infection or inflammation.\n- The patient's BUN level was within normal range at 18 mg/dL, indicating normal kidney function.\n- The patient's total cholesterol level was borderline high at 215 mg/dL, which may indicate a risk of cardiovascular disease.\n\n#### Mismatches:\n- The patient's potassium level was not measured due to hemolysis, which is a potential issue that needs to be addressed.\n- The patient's sodium level was not measured due to a hemolysis issue, which is a potential issue that needs to be addressed."
}

LAB_SAMPLES = [
    {"name": "sample_1", "file": lab_1},
]

import pathlib
import os

os.makedirs("test_results/llm", exist_ok=True)

import pytest
from unittest.mock import patch 
import json

@patch("ml_core.src.ml_core.pipeline.summarizer")
@patch("ml_core.src.ml_core.pipeline.document_reader")
@pytest.mark.parametrize("test, expected", [
    (lab_1, lab_result1_expected)
])

def test_pipeline(mock_summarizer, mock_document_reader, test, expected):

    mock_summarizer.return_value.summarize_content.return_value = {
        lab_result1_expected["summary_text"]
    }

    # Extraction
    mock_document_reader.return_value.extract_text_from_pdf.return_value = {
        lab_result1_expected["extracted_text"]
    }

    # Chunking
    chunked_text = chunk_text(lab_result1_expected["extracted_text"])

    # Cleaning the chunks
    cleaned_text = clean_and_normalize_text(chunked_text)

    cleaned_text_strings = [
        doc.page_content
        for doc in cleaned_text
        if doc.page_content.strip()
    ]

    # vector_store = embed_chunks_and_store_in_vector_db(cleaned_text)

    # Extracting diseases
    diseases = get_negative_entities(cleaned_text_strings)
        
    # Extracting lab results
    lab_results = extract_labs(cleaned_text)

    if isinstance(lab_results, str):
        lab_results = json.loads(lab_results)

    # retriever = vector_store.as_retriever(search_kwargs={"k" : 4})

    # return vector_store, retriever, cleaned_text

    result = {
        "extracted_text": lab_result1_expected["extracted_text"],
        "diseases_json": diseases,
        "labs_json": lab_results,
        "summary_text": lab_result1_expected["summary_text"],
    }

    assert result == lab_result1_expected




