import re
from langchain_text_splitters import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from ml_core.logging_utils import logger, CentralizedLogger, time_metrics
import fitz

from ml_core.pipeline.resources import get_resources

logger = CentralizedLogger.get_logger(__name__)


@time_metrics()
def extract_text_from_pdf_with_docling(file) -> str:
    """
    Extracts text from PDF using Docling with rapidOCR
    """
    converter = get_resources().converter

    try:
        doc = converter.convert(file).document
        mark_doc = doc.export_to_markdown()
    except Exception as e:
        logger.error(f"Failed to extract text from pdf: {e}")
        raise
    return mark_doc


@time_metrics()
def extract_text_with_pymupdf(file) -> str:
    """
    Extracts text from pdf without OCR. Uses fitz(pymupdf)
    """
    doc = fitz.open(file)

    text = ""

    for page_num in range(len(doc)):
        page = doc.load_page(page_num)
        page_text = page.get_text()
        text += page_text

    return text


@time_metrics()
def extract_text_from_pdf(file):
    try:
        text = extract_text_with_pymupdf(file)
    except Exception as e:
        logger.warning("Could not complete extraction using PyMuPDF", exc_info=e)
        text = extract_text_from_pdf_with_docling(file)

    return text


@time_metrics()
def chunk_text(raw_text):
    """
    Two-stage text splitter that guarantees chunks never exceed the token limitations
    of downstream token-classification models, regardless of whether input is Markdown or plain text.
    """
    # Stage 1: Attempt to split structural elements on Markdown headers
    headers_to_split_on = [("##", "Header")]
    markdown_splitter = MarkdownHeaderTextSplitter(
        headers_to_split_on=headers_to_split_on,
        strip_headers=False,
    )
    
    # If the text has markdown headers, it splits it structurally.
    # If it's plain text from PyMuPDF, it safely returns a single-item list containing the whole text.
    structural_chunks = markdown_splitter.split_text(raw_text)
    
    # Stage 2: Sub-split large blocks to enforce token thresholds safety
    # Max chunk size ~1500 characters roughly translates to ~350-400 tokens, 
    # leaving a comfortable safety buffer inside the model's 512 token budget.
    recursive_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1500,
        chunk_overlap=200,
        length_function=len,
        separators=["\n\n", "\n", " ", ""]
    )
    
    final_splits = []
    for chunk in structural_chunks:
        # If the structural section is small enough, keep it intact
        if len(chunk.page_content) <= 1500:
            final_splits.append(chunk)
        else:
            # Sub-split the massive section while preserving header metadata
            sub_chunks = recursive_splitter.split_documents([chunk])
            final_splits.extend(sub_chunks)
            
    return final_splits

@time_metrics()
def clean_and_normalize_text(all_splits):
    """
    Clean raw text extracted from PDF before PDF processing
    """
    for i in range(len(all_splits)):
        if "Header" in all_splits[i].metadata and all_splits[i].metadata["Header"] == "Comments":
            all_splits[i].page_content = ""

        content = all_splits[i].page_content
        cleaned = re.sub(r"\|", "", content)
        cleaned = re.sub(r"-{2,}", "", cleaned)
        cleaned = re.sub(r"\\n", " ", cleaned)
        cleaned = re.sub(r" +", " ", cleaned)

        all_splits[i].page_content = cleaned

    return all_splits


def clean_unchunked_text(content):
    cleaned = re.sub(r"\|", "", content)
    cleaned = re.sub(r"-{2,}", "", cleaned)
    cleaned = re.sub(r"[\r\n]+", " ", cleaned)
    cleaned = re.sub(r"\s+", " ", cleaned)
    cleaned = cleaned.strip()
    return cleaned


@time_metrics()
def embed_chunks_and_store_in_vector_db(all_splits):
    """
    Embeds the Chunks generated by the Semantic Chunker. Maybe well reuse the ones created during chunking
    """
    embeddings = get_resources().embeddings
    vectorstore = Chroma.from_documents(
        all_splits,
        embeddings,
        persist_directory="./chroma_db"
    )

    return vectorstore
