import re
from pathlib import Path
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter
from langchain_experimental.text_splitter import SemanticChunker
from langchain_huggingface import HuggingFaceEmbeddings
from transformers import AutoModel
from sentence_transformers import SentenceTransformer
from langchain_community.vectorstores import Chroma
from docling.document_converter import DocumentConverter
from apps.api.app.core.logger_setup import logger, CentralizedLogger, time_metrics
import os
import fitz
from ml_core.config import SENTENCE_TRANSFORMER_PATH, MODELS_BASE_PATH


from ml_core.src.ml_core.pipeline.disease_extractor import get_negative_entities

os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["HF_HUB_OFFLINE"] = "1"

logger = CentralizedLogger.get_logger(__name__)

# Docling doc converter
converter = DocumentConverter()

# Embedding model
# model_name = "dmis-lab/biobert-base-cased-v1.1"
model_name = str("ml_core/src/ml_core/models/cached_models/models--sentence-transformers--all-MiniLM-L6-v2/snapshots/c9745ed1d9f207416be6d2e6f8de32d1f16199bf")

embeddings = HuggingFaceEmbeddings(model_name=SENTENCE_TRANSFORMER_PATH,
                                    cache_folder=f"{MODELS_BASE_PATH}",
                                    model_kwargs={'device': 'cpu'})

@time_metrics()
def extract_text_from_pdf_with_docling(file) -> str:
    """
    Extracts text from PDF using Docling with rapidOCR
    """

    try:
       doc = converter.convert(file).document
       mark_doc = doc.export_to_markdown()
       

    except Exception as e:
        logger.error(f"Failed to extract text from pdf: {e}")
        raise 
    return mark_doc

@time_metrics()
def extract_text_with_pymupdf(file) -> str:
    """
    Extracts text from pdf without OCR. Uses fitz(pymupdf)
    """
    doc = fitz.open(file)

    text = ""

    for page_num in range(len(doc)):
        page = doc.load_page(page_num)

        page_text = page.get_text()

        text += page_text

    return text

@time_metrics()
def extract_text_from_pdf(file):
    try:
        text = extract_text_with_pymupdf(file)
    except Exception as e:
        logger.warning("Could not complete extraction using PyMuPDF", exc_info=e)

        text = extract_text_from_pdf_with_docling(file)

    return text

@time_metrics()
def chunk_text(markdown_file):
    # headers_to_split_on = [
    # ("##", "Header")]
    # # markdown header splitter
    # splitter = MarkdownHeaderTextSplitter(
    #    headers_to_split_on=headers_to_split_on,
    #     strip_headers=False
    # )
    # # markdown header splitter
    # all_splits = splitter.split_text(markdown_file)

    # Semantic chunker
    splitter = SemanticChunker(
            embeddings,
            breakpoint_threshold_type="percentile",
            breakpoint_threshold_amount=80
    )

    all_splits = splitter.create_documents([markdown_file])

    # splitter = RecursiveCharacterTextSplitter(
    #    chunk_size=512,
    #    chunk_overlap=200,
    #    length_function=len,
    #    is_separator_regex=False
    # )

    # all_splits = splitter.create_documents([markdown_file])

    return all_splits

@time_metrics()
def clean_and_normalize_text(all_splits):
    """
    Clean raw text extracted from PDF before PDF processing
    """

    for i in range(len(all_splits)):
        if "Header 2" in all_splits[i].metadata and all_splits[i].metadata["Header 2"] == '## Comments':
            all_splits[i].page_content = ""

        content = all_splits[i].page_content
        cleaned = re.sub(r"\|", "",  content)
        cleaned = re.sub(r"-{2,}", "", cleaned)
        cleaned = re.sub(r"\\n", " ", cleaned)
        cleaned = re.sub(r" +", " ", cleaned)

        all_splits[i].page_content = cleaned

    return all_splits

@time_metrics()
def embed_chunks_and_store_in_vector_db(all_splits):
    """
    Embeds the Chunks generated by the Semantic Chunker. Maybe well reuse the ones created during chunking
    """
    vectorstore = Chroma.from_documents(
        all_splits,
        embeddings,
        persist_directory="./chroma_db"
    )

    return vectorstore

# import json
# file_path = Path("samplePmedReport.pdf")

# markdown = extract_text_from_pdf(file_path)

# chunks = chunk_text(markdown)

# chunks = clean_and_normalize_text(chunks)
    
# entities = []
# Path("samplePmedReport_md.md").write_text(str(chunks))

# for split in range(len(chunks)):
#     # print(f"chunk {split}\n {chunks[split]}")
#     content = chunks[split].page_content

#     entities.append(get_negative_entities(content))

# Path("samplePmedReport_md.json").write_text(json.dumps(entities))
    